# Generated by Django 2.1.7 on 2019-05-09 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=255)),
                ('algorithm_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('parameter1', models.CharField(max_length=5)),
                ('parameter2', models.CharField(max_length=5)),
                ('parameter3', models.CharField(max_length=5)),
                ('progress1', models.DecimalField(decimal_places=0, max_digits=3)),
                ('progress2', models.DecimalField(decimal_places=0, max_digits=3)),
                ('progress3', models.DecimalField(decimal_places=0, max_digits=3)),
                ('plane_data1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plane_data2', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plane_data3', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plane_data4', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(max_length=12)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Algorithm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
