# Generated by Django 2.1.7 on 2019-04-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(max_length=255)),
                ('algorithm_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.CharField(max_length=5)),
                ('parameter2', models.CharField(max_length=5)),
                ('parameter3', models.CharField(max_length=5)),
                ('parameter4', models.CharField(max_length=5)),
                ('parameter5', models.CharField(max_length=5)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Algorithm')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default='password', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='surname', max_length=55),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
